# Whether this GitHub repo is for a CC-led engineering project
engineering_project: true
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
# Slack channel name
slack: 'cc-dev-browser-extension'
