name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        run: |
          npm ci
          npm run lint
      - name: Formatting
        run: |
          npm ci
          npm run prettier:check
      - name: Tests
        run: |
          npm ci
          npm run test
        env:
          CI: true
